# 接口请求公共url
environment:
  executor: suanmiao
  base_url: http://www.suanmiao.site:8888/

# 数据库连接配置
mysql:
  host: 127.0.0.1
  port: 3306
  database: platform
  username: root
  password: 123456

# 日志配置
log_level:
  global: DEBUG
  file: INFO
